golos:
  #api: https://api-golos.blckchnd.com
  api: https://apibeta.golos.today
  chain_id: 782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de12
spring:
  data:
    rest:
      max-page-size: 50
    web:
      pageable:
        max-page-size: 50
  datasource:
    driverClassName: org.h2.Driver
    username: ebot
    password: ebot
    url: jdbc:h2:./ebot.db;AUTO_SERVER=TRUE
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    #generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      search:
        default:
          indexmanager: elasticsearch
          elasticsearch:
            host: localhost:9200
            index_schema_management_strategy: drop-and-create
            required_index_status: yellow
  codec:
    max-in-memory-size: 30MB

ebot:
  cron: 0 */5 * * * *

cmc:
  cron: 0 0 */6 * * *
  api-key: b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c
  api-url: https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  read-count: 5000
  # max age of price info in minutes
  max-age-minutes: 1440

